# Generated by Django 5.1 on 2024-08-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Entree', 'Entree'), ('Appetizer', 'Appetizer'), ('Beverage', 'Beverage')], max_length=100),
        ),
    ]
