# Generated by Django 5.1 on 2024-08-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Entree', 'Entree'), ('Beverage', 'Beverage'), ('Dessert', 'Dessert'), ('Appetizer', 'Appetizer')], max_length=100),
        ),
    ]
