# Generated by Django 5.1 on 2024-08-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Beverage', 'Beverage'), ('Dessert', 'Dessert'), ('Entree', 'Entree')], max_length=100),
        ),
    ]
