# Generated by Django 5.1 on 2024-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Entree', 'Entree'), ('Appetizer', 'Appetizer'), ('Beverage', 'Beverage'), ('Dessert', 'Dessert')], max_length=100),
        ),
    ]
