# Generated by Django 5.1 on 2024-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Entree', 'Entree'), ('Beverage', 'Beverage'), ('Appetizer', 'Appetizer')], max_length=100),
        ),
    ]
