# Generated by Django 5.1 on 2024-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Dessert', 'Dessert'), ('Entree', 'Entree'), ('Beverage', 'Beverage')], max_length=100),
        ),
    ]
